更新 558-793 bosses_and_skill_points.json
miao0425/Create_Chronicles_ZH_CN pull request #1
Opened 2024-03-22 04:08 UTC by SlimeSB

2024-03-27 05:01 UTC, miao0425 commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests46.title": "&9蔚蓝天空&f:星熠破灭之树幽冥",
```suggestion
	"ftbquests.chapter.bosses_and_skill_points.quests46.title": "&9蔚蓝天空&f:星熠破灭之树",
```

2024-03-27 05:01 UTC, miao0425 commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests45.title": "&9蔚蓝天空&f:幽咽蛛王幽冥",
```suggestion
	"ftbquests.chapter.bosses_and_skill_points.quests45.title": "&9蔚蓝天空&f:幽咽蛛王,
```

2024-03-27 05:02 UTC, miao0425 commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests44.title": "&9蔚蓝天空&f:召唤师幽冥",
```suggestion
	"ftbquests.chapter.bosses_and_skill_points.quests44.title": "&9蔚蓝天空&f:召唤师",
```

2024-03-27 05:03 UTC, miao0425 commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests43.title": "&9蔚蓝天空&f:炼金术师",
```suggestion
	"ftbquests.chapter.bosses_and_skill_points.quests43.title": "&9蔚蓝天空&f:炼金术士",
```

2024-03-27 05:10 UTC, miao0425 commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests32.title": "&3幽冥&f:潜行者",
```suggestion
	"ftbquests.chapter.bosses_and_skill_points.quests32.title": "&3幽冥&f:追猎者",
```

2024-03-27 05:10 UTC, miao0425 commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests32.title": "&3幽冥&f:潜行者",
https://github.com/miao0425/mods_zh_cn/blob/main/1.19/deeperdarker/lang/zh_cn..json

2024-03-27 05:14 UTC, miao0425 commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests22.title": "&2主世界&f:尸巫",
```suggestion
	"ftbquests.chapter.bosses_and_skill_points.quests22.title": "&2主世界&f:巫妖",
```

2024-03-27 05:15 UTC, miao0425 commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests22.title": "&2主世界&f:尸巫",
https://www.mcmod.cn/item/777374.html
下文同理

2024-03-27 05:17 UTC, miao0425 requested changes
1

2024-03-28 10:30 UTC, SlimeSB commented on kubejs/assets/ftbquests/558-793 bosses_and_skill_points.json
> +	"ftbquests.chapter.bosses_and_skill_points.quests22.title": "&2主世界&f:尸巫",
包含改动，暂搁置

2024-03-28 10:32 UTC, merged